;==============================================================================
; Explorer sprite compositing
;
; Register contract for exported entries:
;   DrawPlayer/DrawPlayerFire: Inputs none; read explorer pose/position state.
;   DrawPlayerPattern: Input U = eight 16-byte horizontal phases.
;   Outputs: explorer OR-composited onto the display.
;   Clobbers: A, B, X, Y, U, CC; S balanced; DP unchanged; returns with the
;     bitmap display plane selected.
;==============================================================================

;------------------------------------------------------------------------------
; Explorer sprite
;------------------------------------------------------------------------------
DrawPlayer:
        ; During horizontal motion, the directional firing silhouettes make the
        ; facing direction explicit. Vertical/idle motion uses walking poses.
        lda     PlayerMoveDirection
        cmpa    #PLAYER_DIR_RIGHT
        beq     DrawPlayerMoveRight
        cmpa    #PLAYER_DIR_LEFT
        beq     DrawPlayerMoveLeft
        ldu     #PlayerWalkShifted0
        tst     PlayerAnimationFrame
        beq     DrawPlayerPattern
        ldu     #PlayerWalkShifted1
        bra     DrawPlayerPattern
DrawPlayerMoveRight:
        ldu     #PlayerFireRightShifted
        bra     DrawPlayerPattern
DrawPlayerMoveLeft:
        ldu     #PlayerFireLeftShifted
        bra     DrawPlayerPattern

DrawPlayerFire:
        ldu     #PlayerFireRightShifted
        tst     PlayerFacing
        bpl     DrawPlayerPattern
        ldu     #PlayerFireLeftShifted

; Each row of the U-addressed artwork contains the left and right bitmap bytes
; for an 8-pixel sprite shifted across a byte boundary.
DrawPlayerPattern:
        lda     PlayerPixelX
        anda    #$07
        sta     PlayerHorizontalPhase
        ldb     #16
        mul
        leau    d,u

        lda     PlayerPixelX
        lsra
        lsra
        lsra
        adda    #LEVEL_SCREEN_COL
        sta     PlayerDrawColumn
        ldb     PlayerPixelY
        addb    #LEVEL_SCREEN_ROW*TEXT_CELL_HEIGHT
        lda     #VIDEO_BYTES_PER_ROW
        mul
        addb    PlayerDrawColumn
        adca    #0
        tfr     d,x

        jsr     SelectBitmapPlane
        pshs    x
        ldy     #8
DrawPlayerBitmapRow:
        pulu    d
        ora     ,x
        orb     1,x
        std     ,x
        leax    VIDEO_BYTES_PER_ROW,x
        leay    -1,y
        bne     DrawPlayerBitmapRow

        puls    x
        jsr     SelectColorPlane
        lda     #COLOR_PLAYER
        ldy     #8
DrawPlayerColorRow:
        sta     ,x
        tst     PlayerHorizontalPhase
        beq     DrawPlayerColorLeftOnly
        sta     1,x
DrawPlayerColorLeftOnly:
        leax    VIDEO_BYTES_PER_ROW,x
        leay    -1,y
        bne     DrawPlayerColorRow
        jmp     SelectBitmapPlane

; Restore every map cell touched by the old arbitrary-pixel 8x8 footprint.
; A diagonal footprint is not generated by the movement rules, but handling
; the full 2x2 case keeps the renderer correct for future effects.
