#!/usr/bin/env node

import fs from "node:fs";

/*
 * Build-time room packer.
 *
 * Source of truth: readable FCC rows inside src/game/data.asm's disabled
 * assembly block. RoomTemplatePointers defines output order, so adding or
 * reordering a room requires no second JavaScript list.
 *
 * Encoding: two tiles per byte, first tile in the high nibble. PackedTileValues
 * in data.asm performs the inverse nibble-to-ASCII lookup at runtime. With
 * 30 * 22 = 660 cells, each immutable room occupies 330 bytes.
 *
 * The generated assembly belongs in build/maps-packed.asm and must never be
 * edited by hand.
 */
const [sourcePath, outputPath] = process.argv.slice(2);
if (!sourcePath || !outputPath) {
  throw new Error("usage: pack-maps.mjs <game-data.asm> <packed-maps.asm>");
}

const source = fs.readFileSync(sourcePath, "utf8");
const tileCodes = new Map(
  [..."#.KTSVARD"].map((tile, code) => [tile, code]),
);

function blockFor(label) {
  // Return the assembly text owned by one global label.
  const marker = `${label}:`;
  const start = source.indexOf(marker);
  if (start < 0) throw new Error(`missing data label ${label}`);
  const rest = source.slice(start + marker.length);
  const next = rest.search(/^[A-Za-z_][A-Za-z0-9_]*:/m);
  return next < 0 ? rest : rest.slice(0, next);
}

const mapNames = [
  ...blockFor("RoomTemplatePointers").matchAll(/^\s*fdb\s+(.+)$/gm),
].flatMap((match) => match[1].split(",").map((value) => value.trim()));

function rowsFor(label) {
  return [...blockFor(label).matchAll(/^\s*fcc\s+"([^"]*)"/gm)].map(
    (match) => match[1],
  );
}

function packedBytesFor(label) {
  // Validate size and vocabulary again even though validate-content runs first;
  // pack-maps is also useful as a standalone tool.
  const cells = rowsFor(label).join("");
  if (cells.length !== 660) {
    throw new Error(`${label} has ${cells.length} cells, expected 660`);
  }
  const bytes = [];
  for (let index = 0; index < cells.length; index += 2) {
    const high = tileCodes.get(cells[index]);
    const low = tileCodes.get(cells[index + 1]);
    if (high === undefined || low === undefined) {
      throw new Error(`${label} contains an unknown tile`);
    }
    bytes.push((high << 4) | low);
  }
  return bytes;
}

const lines = [
  "; Generated by tools/pack-maps.mjs. Do not edit by hand.",
  "; Each byte stores two room tiles, high nibble first.",
  "",
];

for (const name of mapNames) {
  const bytes = packedBytesFor(name);
  lines.push(`${name}:`);
  for (let index = 0; index < bytes.length; index += 16) {
    const chunk = bytes
      .slice(index, index + 16)
      .map((value) => `$${value.toString(16).toUpperCase().padStart(2, "0")}`)
      .join(",");
    lines.push(`        fcb     ${chunk}`);
  }
  lines.push("");
}

fs.writeFileSync(outputPath, `${lines.join("\n")}\n`);
